In [14]:
from pycaret.classification import *

import pandas as pd

In [2]:
data = pd.read_csv("Churn_Modelling.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

## Pre-processing

PyCaret supports a simple setup module that applies 25+ pre-processing techniques

In [4]:
s = setup(data, target = 'Exited', ignore_features = ['CustomerId', 'Surname', 'RowNumber'])

## Modelling

In [5]:
best_model = compare_models(sort='Recall')

Creating a model in addition to 10 folds cross validation

In [6]:
GBC = create_model('gbc')

In [7]:
print(GBC)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8750, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [8]:
GBC.feature_importances_

array([2.41554756e-02, 3.53769389e-01, 8.43374038e-02, 1.84710985e-02,
       7.83434406e-04, 6.54149946e-02, 1.50088690e-03, 1.30579125e-02,
       4.79089499e-04, 4.49944142e-04, 2.34992325e-04, 4.10447539e-04,
       6.25664341e-04, 9.02744951e-04, 4.94936476e-04, 2.21589574e-05,
       1.00102160e-03, 0.00000000e+00, 7.66704292e-04, 4.26287709e-02,
       1.89832237e-01, 7.26428877e-02, 1.95798508e-02, 0.00000000e+00,
       1.08437954e-01])

It also supports randomized cross validation in hyperparameter tuning

In [9]:
GBC2 = tune_model(GBC)

### Ensemble

In [10]:
best3 = compare_models(n_select=3)

Soft voting method

In [11]:
soft_voting = blend_models(best3)

## Results & Accuracy

In [12]:
evaluate_model(soft_voting)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [13]:
evaluate_model(GBC)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

There are still other features supported by the library (predicting new data, connecting to a cloud server, saving and loading models, optimizing models)